name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build archive
        run: |
          xcodebuild \
          -project "BLE Terminal.xcodeproj" \
          -scheme "BLE Terminal" \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/BLETerminal.xcarchive \
          archive

      - name: Export IPA
        run: |
          mkdir -p build/ipa
          xcodebuild -exportArchive \
          -archivePath build/BLETerminal.xcarchive \
          -exportPath build/ipa \
          -exportOptionsPlist ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ipa
