name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build for device
        run: |
          xcodebuild \
          -project "BLE Terminal.xcodeproj" \
          -scheme "BLE Terminal" \
          -sdk iphoneos \
          CODE_SIGNING_ALLOWED=NO \
          build

      - name: Upload app bundle
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ~/Library/Developer/Xcode/DerivedData
